name: build-catalog CI

on:
  push:
    paths:
      - '**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      WORKING-DIRECTORY: .

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.WORKING-DIRECTORY}}

      - name: Build App
        run: npm run build
        working-directory: ${{env.WORKING-DIRECTORY}}

  build_and_push:
    name: Build Docker image and push to ghcr
    needs: build
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: build-catalog
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build catalog Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/tmogdans/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.output.labels }}